# Generated by Django 4.2.16 on 2024-09-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeRecords', models.CharField(max_length=6)),
                ('Diagnosis', models.TextField(max_length=500)),
                ('Treatment', models.TextField(max_length=500)),
                ('Forecast', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('WeightPounds', models.IntegerField(null=True)),
                ('Measure', models.IntegerField(null=True)),
                ('Active', models.BooleanField()),
                ('IdPatients', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Patients.patients')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
    ]
