# Generated by Django 4.2.16 on 2024-09-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Date',
            field=models.DateField(),
        ),
    ]
