# Generated by Django 4.2.16 on 2024-09-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patients', '0001_initial'),
        ('MedicalStaff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeQuotes', models.CharField(max_length=10)),
                ('Reason', models.TextField(max_length=500)),
                ('State', models.CharField(max_length=50)),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField()),
                ('IdPatients', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Patients.patients')),
                ('MedicalStaffId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='MedicalStaff.medicalstaff')),
            ],
            options={
                'db_table': 'Citas',
            },
        ),
    ]
