# Generated by Django 4.2.16 on 2024-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChargeCode', models.CharField(max_length=5)),
                ('NameCharges', models.CharField(max_length=100)),
                ('Active', models.BooleanField()),
            ],
            options={
                'db_table': 'Charges',
            },
        ),
    ]
