# Generated by Django 4.2.16 on 2024-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdentityCard', models.CharField(max_length=20, null=True)),
                ('Firstname', models.CharField(max_length=200)),
                ('Middlename', models.CharField(max_length=150, null=True)),
                ('Surnames', models.CharField(max_length=200)),
                ('Sexo', models.CharField(max_length=50)),
                ('Age', models.IntegerField(null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Address', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
